version: "3.9"
services:
  db:
    image: mariadb:10.4
    container_name: mysql_dev_data
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=testdev
    ports:
      - "3306:3306"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d:ro
      - ./mysql_data:/var/lib/mysql:rw
volumes:
  data:
    driver: local
